<?php
$_ENCODINGS = array(
    array('title'=>'West European', 'items'=>array(
        array('title'=>'Western', 'encoding'=>'ISO-8859-1'),
        array('title'=>'Western', 'encoding'=>'ISO-8859-15'),
        array('title'=>'Western', 'encoding'=>'IBM-850'),
        array('title'=>'Western', 'encoding'=>'MacRoman'),
        array('title'=>'Western', 'encoding'=>'Windows-1252'),
        array('title'=>'Ciltic', 'encoding'=>'ISO-8859-14'),
        array('title'=>'Greek', 'encoding'=>'ISO-8859-7'),
        array('title'=>'Greek', 'encoding'=>'MacGreek'),
        array('title'=>'Greek', 'encoding'=>'Windows-1253'),
        array('title'=>'Icelandic', 'encoding'=>'MacIcelandic'),
        array('title'=>'Nordic', 'encoding'=>'ISO-8859-10'),
        array('title'=>'South European', 'encoding'=>'ISO-8859-3'),
    )),
    array('title'=>'East European', 'items'=>array(
        array('title'=>'Baltic', 'encoding'=>'ISO-8859-4'),
        array('title'=>'Baltic', 'encoding'=>'ISO-8859-13'),
        array('title'=>'Baltic', 'encoding'=>'Windows-1257'),
        array('title'=>'Central European', 'encoding'=>'IBM-852'),
        array('title'=>'Central European', 'encoding'=>'ISO-8859-2'),
        array('title'=>'Central European', 'encoding'=>'MacCE'),
        array('title'=>'Central European', 'encoding'=>'Windows-1250'),
        array('title'=>'Croatian', 'encoding'=>'MacCroatian'),
        array('title'=>'Cyrillic', 'encoding'=>'IBM-855'),
        array('title'=>'Cyrillic', 'encoding'=>'ISO-8859-5'),
        array('title'=>'Cyrillic', 'encoding'=>'ISO-IR-111'),
        array('title'=>'Cyrillic', 'encoding'=>'KOI8-R'),
        array('title'=>'Cyrillic', 'encoding'=>'MacCyrillic'),
        array('title'=>'Cyrillic', 'encoding'=>'Windows-1251'),
        array('title'=>'Cyrillic/Russian', 'encoding'=>'IBM-866'),
        array('title'=>'Cyrillic/Ukrainian', 'encoding'=>'KOI8-U'),
        array('title'=>'Romanian', 'encoding'=>'ISO-8859-16'),
        array('title'=>'Romanian', 'encoding'=>'MacRomanian'),
    )),
    array('title'=>'East Asian', 'items'=>array(
        array('title'=>'Chinese Simplified', 'encoding'=>'GB2312'),
        array('title'=>'Chinese Simplified', 'encoding'=>'GBK'),
        array('title'=>'Chinese Simplified', 'encoding'=>'GB18030'),
        array('title'=>'Chinese Simplified', 'encoding'=>'HZ'),
        array('title'=>'Chinese Simplified', 'encoding'=>'ISO-2022-CN'),
        array('title'=>'Chinese Traditional', 'encoding'=>'Big5'),
        array('title'=>'Chinese Traditional', 'encoding'=>'Big5-HKSCS'),
        array('title'=>'Chinese Traditional', 'encoding'=>'EUC-TW'),
        array('title'=>'Japanese', 'encoding'=>'EUC-JP'),
        array('title'=>'Japanese', 'encoding'=>'IOS-2022-JP'),
        array('title'=>'Japanese', 'encoding'=>'Shift_JIS'),
        array('title'=>'Korean', 'encoding'=>'EUC-KR'),
        array('title'=>'Korean', 'encoding'=>'UHC'),
        array('title'=>'Korean', 'encoding'=>'JOHAB'),
        array('title'=>'Korean', 'encoding'=>'ISO-2022-KR'),
    )),
    array('title'=>'SE & SW Asian', 'items'=>array(
        array('title'=>'Armenian', 'encoding'=>'ARMSCII-8'),
        array('title'=>'Thai', 'encoding'=>'TIS-620'),
        array('title'=>'Thai', 'encoding'=>'ISO-8859-1'),
        array('title'=>'Thai', 'encoding'=>'Windows-874'),
        array('title'=>'Turkish', 'encoding'=>'IBM-857'),
        array('title'=>'Turkish', 'encoding'=>'ISO-8859-9'),
        array('title'=>'Turkish', 'encoding'=>'MacTurkish'),
        array('title'=>'Turkish', 'encoding'=>'Windows-1254'),
        array('title'=>'Vietnamese', 'encoding'=>'TCVN'),
        array('title'=>'Vietnamese', 'encoding'=>'VISCII'),
        array('title'=>'Vietnamese', 'encoding'=>'VPS'),
        array('title'=>'Vietnamese', 'encoding'=>'Windows-1258'),
        array('title'=>'Hindi', 'encoding'=>'MacDevanagari'),
        array('title'=>'Gujarati', 'encoding'=>'MacGujarati'),
        array('title'=>'Gurmukhi', 'encoding'=>'MacGurmukhi'),
    )),
    array('title'=>'Middle Eastern', 'items'=>array(
        array('title'=>'Arabic', 'encoding'=>'ISO-8859-6'),
        array('title'=>'Arabic', 'encoding'=>'Windows-1256'),
        array('title'=>'Arabic', 'encoding'=>'IBM-864'),
        array('title'=>'Hebrew', 'encoding'=>'ISO-8859-8-I'),
        array('title'=>'Hebrew', 'encoding'=>'Windows-1255'),
        array('title'=>'Hebrew', 'encoding'=>'ISO-8859-8'),
        array('title'=>'Hebrew', 'encoding'=>'IBM-862'),
    )),
    array('title'=>'Unicode', 'items'=>array(
        array('title'=>'Unicode', 'encoding'=>'UTF-8'),
        array('title'=>'Unicode', 'encoding'=>'UTF-16 LE'),
        array('title'=>'Unicode', 'encoding'=>'UTF-16 BE'),
    )),
);
?>
